### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by GersonHMG** [horrzs/MyosgQOpenGLWidget#1]
Hi,

Sorry for contacting you through an issue, but I couldn't find another way to do it.

Did you find a solution to this issue? https://github.com/microsoft/vcpkg/issues/39452

I have the same problem.

**Comment by GersonHMG** [comment]
@horrzs

**Comment by HorrZzz** [comment]
No solution found😭

**Comment by GersonHMG** [comment]
fixed :D.
